# Github workflow to run django tests

name: CI Django App Tests

on:
  push:
    branches: [ main ]

jobs:
  testing:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Python 
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django Tests
        working-directory: ./todo_app
        run: python manage.py test
