# Github workflow to run django tests

name: CI Django App Tests

on:
  push:
    branches: [ main ]

jobs:
  testing:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo & setup Python
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '>=3.9.1'

      # - name: Install Python dependencies
      #   uses: py-actions/py-dependency-install@v2
      #   with:
      #     path: "$GITHUB_WORKSPACE/requirements.txt"

      - name: Run migrations
        run: python manage.py migrate

      - name: Run Django Tests
        run: python manage.py test



    
