# Github workflow to run django tests

name: CI Django App Tests

on:
  push:
    branches: [ main ]

jobs:
  testing:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Python 
        uses: actions/setup-python@v2

      - name: Docker build image
        run: docker build -t todoimage . -f Dockerfile
      - name: Docker build container
        run: docker run -d -t --name todocontainer todoimage

      - name: Run migrations & tests in docker
        run: | 
          docker exec -it todocontainer bash
          python manage.py makemigrations
          python manage.py migrate
          python manage.py test
 
