# Github workflow to run django tests

name: CI Django App Tests

on:
  push:
    branches: [ main ]

jobs:
  testing:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo & setup Python
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '>=3.9.1'

      - name: Install Python dependencies
        run: |
          python -m pip install wheel
          pip install -r requirements.txt

      - name: Run migrations
        run: |
          python ./todo_app/manage.py makemigrations
          python ./todo_app/manage.py migrate

      - name: Run Django Tests
        working-directory: ./todo_app
        run: python manage.py test



    
