# Github workflow to run django tests

name: CI Django App Tests

on:
  push:
    branches: [ main ]

jobs:
  testing:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo & setup Python
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '>=3.9.1'
      
      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install requirements
        run: |
          echo $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE
          pip install -r requirements.txt

      - name: Run migrations
        run: python manage.py migrate

      - name: Run Django Tests
        run: python manage.py test



    
